typedef builtin_type ccdsw;
typedef builtin_type locker;
typedef builtin_type sect;
typedef builtin_type regexp;
unsigned int ccd_heap_maxmem();
unsigned int ccd_heap_usedmem();
ccdsw ccd_stopwatch_begin();
double ccd_stopwatch_end(ccdsw sw);
double ccd_stopwatch_disp(ccdsw sw, char *msg);
int ccd_io_fexts(char *file, unsigned int path);
int ccd_io_write(char *file, unsigned int path, void *data, int len);
sect selector(char *funcName);
void performSelector(sect sel, void *arg);
void exec(char *c_code);
void async_delay(sect sel, void *arg, double seconds);
void async_perform(void);
void thread_start(sect sel, void *arg);
int thread_core_maxium();
int thread_maxium();
int thread_total();
locker thread_locker();
void thread_locker_read(locker t);
void thread_locker_write(locker t);
void thread_locker_unlock(locker t);
void sleep(unsigned int second);
int usleep(unsigned int usecond);
regexp regexp_build(char *regex);
char** regexp_match(char *regex, int *match_size);
