void  strcpy(char *dst, char *src);
void  strncpy(char *dst, char *src, int n);
int  strcmp(char *lhs, char *rhs);
int  strncmp(char *lhs, char *rhs, int n);
void  strcat(char *dest, char *src);
char  *index(char *s, int c);
char  *rindex(char *s, int c);
int  strlen(char *);
void  memset(void *, int val, int count);
void  memcpy(void *dst, void *src, int count);
int  memcmp(void *lhs, void *rhs, int count);
